// Generated by dts-bundle-generator v9.4.0

import { ModuleWithProviders } from '@angular/core';

export declare class SampleModule {
	static forRoot(): ModuleWithProviders<unknown>;
	static ɵfac: i0.ɵɵFactoryDeclaration<unknown, never>;
	static ɵmod: i0.ɵɵNgModuleDeclaration<unknown, never, never, never>;
	static ɵinj: i0.ɵɵInjectorDeclaration<unknown>;
}

export {};
